---
title: "18f0371 talha Zafar"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}



library(pdftools)
library(tesseract)
library(magrittr)
library(tidyverse)
library(magick)


df=data.frame(matrix('',ncol = 0,nrow = 15))


# for (i in 1:48) {
#   pth=paste('C:/Users/Talha/Desktop/E10/a (',').pdf',sep=as.character(i))
#   print(pth)
#   pdf_convert(
#     pth,
#     format = "png",
#     pages = 2,
#     filenames = NULL,
#     dpi = 72,
#     antialias = TRUE,
#     opw = "",
#     upw = "",
#     verbose = TRUE
#   )
#   
# }



#pth=paste('C:/Users/Talha/Documents/a (',')_2.png',sep=as.character(i))
  

raw_img=image_read('C:/Users/Talha/Documents/a (1)_2.png')

image_ggplot(raw_img)



```



```{r cars}


raw_img %>% 
  image_crop(geometry_area(350, 0,350, 10)) %>% 
  ocr()

```

## Including Plots


```{r pressure1}
raw_img %>% 
  image_quantize(colorspace = "gray") %>% 
  image_ggplot()
```


```{r pressure2}
fuzz_fun <- function(fuzz){
  raw_img %>% 
    image_quantize(colorspace = "gray") %>% 
    image_transparent(color = "white", fuzz=fuzz) %>% 
    image_background("white") %>% 
    image_crop(geometry_area(350, 0,350, 10))
}

fuzz_fun(20)
```


```{r pressure3}
no_grid <- raw_img %>% 
  image_quantize(colorspace = "gray") %>% 
  image_transparent(color = "white", fuzz=20) %>% 
  image_background("white") 

image_ggplot(no_grid)
```


```{r pressure4}
no_grid %>% 
  image_negate() %>% 
  image_ggplot()
  
```


```{r pressure5}
no_grid %>%
  image_negate() %>% # negate
  image_morphology(method = "Thinning", kernel = "Rectangle:20x1") %>%
  image_negate() %>% # back to white
  image_ggplot()

  
```


```{r pressure6}
no_grid %>% 
  image_crop(geometry_area(350, 0,350, 10)) %>%
  image_ggplot()

```


```{r pressure7}
no_grid_crop <- no_grid %>% 
  image_crop(geometry_area(350, 0,350, 10))


```


```{r pressure8}
no_grid_crop %>%
  image_ggplot()

```


```{r pressure9}
no_grid_crop %>%
  image_ocr()

```


```{r pressure10}
num_only <- tesseract::tesseract(
  options = list(tessedit_char_whitelist = c(".0123456789 "))
)

no_grid %>% 
  image_quantize(colorspace = 'gray') %>% 
  image_threshold() %>% 
  image_crop(geometry_area(350, 0,350, 10)) %>%
  ocr(engine = num_only)

  
```


```{r pressure11}
combo <- tesseract::tesseract(
  options = list(
    tessedit_char_whitelist = paste0(
      c(letters, LETTERS, " ", ".0123456789 (-)"), collapse = "")
  )
)

raw_text <- no_grid %>%
  image_quantize(colorspace = "gray") %>%
  image_transparent("white", fuzz = 22) %>%
  image_background("white") %>%
  image_threshold() %>%
  image_crop(geometry_area(300, 0,400, 10)) %>%  
  ocr(engine = combo)

```


```{r pressure12}
raw_tibble <- raw_text %>% 
  str_split(pattern = "\n") %>% 
  unlist() %>%
  tibble(data = .) 

raw_tibble$data=gsub(')','',as.character(raw_tibble$data))
raw_tibble$data=gsub('-','',as.character(raw_tibble$data))
col1=raw_tibble[1:7,]
raw_tibble=raw_tibble[-(1:9),]
raw_tibble=raw_tibble[-(11:13),]
col1=col1[-(1:2),]


col1=sub('.*? ','',col1$data)
col1=data.frame(col1)
check=separate(raw_tibble,data ,into = c('retail1','retail2','direct'),sep = '\\ ',extra = 'merge')


      
library(tidyverse)
col1=col1 %>% add_row(col1=check$retail2)
col1
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
